Simple maintenance improvements
Xubuntu/lightdm-gtk-greeter pull request #125
Opened 2022-08-27 14:43 UTC by a1346054

2022-08-29 07:50 UTC, ochosi commented on src/greetermenubar.c
> +    guint             visible_count = 0;
```suggestion
    guint              visible_count = 0;
```

2022-08-29 07:50 UTC, ochosi commented on src/greetermenubar.c
> +    guint             expand_count = 0;
```suggestion
    guint              expand_count = 0;
```

2022-08-29 07:50 UTC, ochosi commented on src/greetermenubar.c
> +    GtkPackDirection  pack_direction;
```suggestion
    GtkPackDirection   pack_direction;
```

2022-08-29 07:52 UTC, ochosi requested changes
Thanks for the cleanups and typo fixes. At least in GitHub's UI it looks as though the variable names without leading * are missing a space (the first variable character should always be aligned).
Please verify/change. Thanks!

Otherwise I think this is ok to merge as is @bluesabre

2022-09-01 14:55 UTC, a1346054 commented
Fixed up that commit with your suggestions, well spotted, thanks.

2022-09-02 11:29 UTC, ochosi approved these changes

2022-09-02 20:15 UTC, merged